export const hotels = [
  {
    id: 1,
    name: 'The Grand London Resort and Spa',
    location: 'Westminster, London',
    image: '/images/h1.jpg',
    rating: '4.6',
    reviews: '2,345',
    price: '72',
    alt: 'The Grand London Resort and Spa',
  },
  {
    id: 2,
    name: 'Barcelona City Suites Deluxe Hotel',
    location: 'Ciutat Vella, Barcelona',
    image: '/images/h2.jpg',
    rating: '4.7',
    reviews: '1,912',
    price: '85',
    alt: 'Barcelona City Suites Deluxe Hotel',
  },
  {
    id: 3,
    name: 'Times Square Premium Stay Hotel',
    location: 'Manhattan, New York',
    image: '/images/h3.jpg',
    rating: '4.9',
    reviews: '3,420',
    price: '95',
    alt: 'Times Square Premium Stay Hotel',
  },
  {
    id: 4,
    name: 'Hilton Roma Luxury Hotel Palace',
    location: 'Vaticano Prati, Rome',
    image: '/images/h4.jpg',
    rating: '4.5',
    reviews: '2,876',
    price: '68',
    alt: 'Hilton Roma Luxury Hotel Palace',
  },
];