export const hotels = [  
  {
    id: 1,
    name: 'Fairmont The Norfolk',
    location: 'Nairobi, Kenya',
    image: '/hotels/fairmont.png',
    rating: '4.8',
    reviews: '2,104',
    price: '310',
    alt: 'Fairmont The Norfolk Hotel in Nairobi',
  },
  {
    id: 2,
    name: 'Villa Rosa Kempinski',
    location: 'Nairobi, Kenya',
    image: '/hotels/kempinski.png',
    rating: '4.7',
    reviews: '1,875',
    price: '290',
    alt: 'Villa Rosa Kempinski in Nairobi',
  },
  {
    id: 3,
    name: 'Finch Hattons Luxury',
    location: 'Tsavo West, Kenya',
    image: '/hotels/finch.jpg',
    rating: '4.9',
    reviews: '820',
    price: '1200',
    alt: 'Finch Hattons Safari Camp in Tsavo West',
  },
  {
    id: 4,
    name: 'Kwetu Nairobi by Hilton',
    location: 'Nairobi, Kenya',
    image: '/hotels/kwetu.png',
    rating: '4.6',
    reviews: '760',
    price: '280',
    alt: 'Kwetu Nairobi by Hilton Hotel',
  },
  {
    id: 5,
    name: 'Tribe Hotel',
    location: 'Nairobi, Kenya',
    image: '/hotels/tribe.png',
    rating: '4.5',
    reviews: '1,156',
    price: '260',
    alt: 'Tribe Hotel Nairobi',
  },
  {
    id: 6,
    name: 'Ngorongoro Serena Lodge',
    location: 'Ngorongoro Crater, Tanzania',
    image: '/hotels/serenangorongoro.jpg',
    rating: '4.7',
    reviews: '890',
    price: '610',
    alt: 'Ngorongoro Serena Safari Lodge in Tanzania',
  },
  {
    id: 7,
    name: 'Melia Serengeti Lodge',
    location: 'Serengeti National Park, Tanzania',
    image: '/hotels/melia.png',
    rating: '4.8',
    reviews: '932',
    price: '840',
    alt: 'Melia Serengeti Lodge in Tanzania',
  },
  {
    id: 8,
    name: 'Singita Sabora Camp',
    location: 'Grumeti Reserve, Tanzania',
    image: '/hotels/singita.png',
    rating: '5.0',
    reviews: '560',
    price: '1500',
    alt: 'Singita Sabora Luxury Tented Camp',
  },
  {
    id: 9,
    name: 'Bisate Lodge',
    location: 'Volcanoes National Park, Rwanda.',
    image: '/hotels/bisate.png',
    rating: '4.9',
    reviews: '645',
    price: '1350',
    alt: 'Bisate Lodge in Volcanoes National Park.',
  },
  {
    id: 10,
    name: 'One&Only Nyungwe',
    location: 'Nyungwe Forest, Rwanda',
    image: '/hotels/one.png',
    rating: '4.8',
    reviews: '678',
    price: '1250',
    alt: 'One&Only Nyungwe House in Rwanda',
  },
  {
    id: 11,
    name: 'Manta Resort',
    location: 'Pemba Island, Tanzania',
    image: '/hotels/manta.jpg',
    rating: '4.9',
    reviews: '589',
    price: '890',
    alt: 'Manta Resort with underwater room in Pemba',
  },
  {
    id: 12,
    name: 'Tulia Zanzibar Resort',
    location: 'Pongwe, Zanzibar',
    image: '/hotels/tulia.jpg',
    rating: '4.7',
    reviews: '755',
    price: '560',
    alt: 'Tulia Unique Beach Resort Zanzibar',
  },
  {
    id: 13,
    name: 'Zuri Zanzibar',
    location: 'Kendwa, Zanzibar',
    image: '/hotels/zuri.jpg',
    rating: '4.8',
    reviews: '895',
    price: '610',
    alt: 'Zuri Zanzibar Beach Resort',
  },
  {
    id: 14,
    name: 'Baraza Resort & Spa',
    location: 'Bwejuu, Zanzibar',
    image: '/hotels/baraza.jpg',
    rating: '4.9',
    reviews: '960',
    price: '670',
    alt: 'Baraza Resort and Spa in Zanzibar',
  },
];
